#!/usr/bin/env bash

export PATH=$PATH:/usr/local/bin

CLUSTER='sudo /usr/sbin/pcs'

SPHINX_MASTER='10.116.27.133'
SPHINX_SLAVE='10.116.27.134'


function main {
  print "> Check cluster status:"
  /opt/cluster/check_cluster.sh || exit 1
  
  print "> Stopping current sphinx reindex process for Sphinx Slave (if any):"
  ssh -t $SPHINX_SLAVE "sudo /etc/init.d/searchd stop"
  sleep 10

  print "> Running sphinx reindex for Sphinx Slave: $SPHINX_SLAVE"
  ssh -t $SPHINX_SLAVE "/usr/local/bin/sphinx_reindex_local $1"
    
  print "> Standby current Sphinx node"
  $CLUSTER cluster standby
    
  print "> Running sphinx reindex for Sphinx Master: $SPHINX_MASTER"
  ssh -t $SPHINX_MASTER "/usr/local/bin/sphinx_reindex_local $1"

  $CLUSTER cluster unstandby
}

function print {
  DEF='\033[0;39m'       #  ${DEF}
  DGRAY='\033[1;30m'     #  ${DGRAY}
  LRED='\033[1;31m'      #  ${LRED}
  LCYAN='\033[1;36m'     #  ${LCYAN}
  LGREEN='\033[1;32m'    #  ${LGREEN}
  LYELLOW='\033[1;33m'   #  ${LYELLOW}
  LBLUE='\033[1;34m'     #  ${LBLUE}
  LMAGENTA='\033[1;35m'  #  ${LMAGENTA}
  if [ -z "$2" ]; then
    echo -e "$LYELLOW$1$DEF"
  else
    echo -e "$LRED ERROR: $1$DEF"
  fi
}

if [[ $1 == '-h' || $1 == '--help' ]]; then
  echo -e "Usage: $0 [--update]"
  echo -e "\t--update \tUpdate sphinx config files first"
  exit
fi

main "$@"
