#!/usr/bin/env bash

ND_DIR="/var/www/apps/current"
NODE_ENV="production"

SPHINX_SRVS=( "user@srv1" "user@srv2" )
SEARCHD="sudo /etc/init.d/searchd"
INDEXER="sudo -u sphinx /usr/bin/indexer"

SPHINX_CONF="/etc/sphinx/conf.d/"
INDEX_DIRS="/usr/local/var/data/"
ORGS=( "orchid" )

export PATH=$PATH:/usr/local/bin

function main {
  for s in "${SPHINX_SRVS[@]}"; do
    print "> Running sphinx_reindex for $s"

    SSH="ssh -t $s"

    $SSH $SEARCHD stop

    print "> Flushing all indexes on $s.."
    $SSH "cd $INDEX_DIRS;
    for d in "'*'"; do
      echo \"removing all files from $INDEX_DIRS"'$d'\""
      rm -i -f -v $INDEX_DIRS"'$d/*'"
    done"

    print "> Create sphinx standart indexes on $s.."
    $SSH $INDEXER --all

    $SSH $SEARCHD start

    cd $ND_DIR &&
    print "> Building sphinx rt indexesi on $s.."
    for o in "${ORGS[@]}"; do
      print "building rt indexes for $o on $s:"
      NODE_ENV=$NODE_ENV node tasks $o/reindex
    done
  done
}

function update_config {
  for s in "${SPHINX_SRVS[@]}"; do
    print "> Running sphinx config update for $s"

    SSH="ssh -t $s"

    print "Updating sphinx config files.."
    cd $ND_DIR &&
    for o in "${ORGS[@]}"; do
      print "updating config: "$SPHINX_CONF$o.conf
      NODE_ENV=$NODE_ENV timeout 5 node tasks $o/sphinx | $SSH "cat > $SPHINX_CONF$o.conf"
    done
  done
}

function print {
  DEF='\033[0;39m'       #  ${DEF}
  DGRAY='\033[1;30m'     #  ${DGRAY}
  LRED='\033[1;31m'      #  ${LRED}
  LCYAN='\033[1;36m'     #  ${LCYAN}
  LGREEN='\033[1;32m'    #  ${LGREEN}
  LYELLOW='\033[1;33m'   #  ${LYELLOW}
  LBLUE='\033[1;34m'     #  ${LBLUE}
  LMAGENTA='\033[1;35m'  #  ${LMAGENTA}
  if [ -z "$2" ]; then
    echo -e "$LCYAN$1$DEF"
  else
    echo -e "$LRED ERROR: $1$DEF"
  fi
}


if [[ $1 == '-h' || $1 == '--help' ]]; then
  echo -e "Usage: $0 [--update]"
  echo -e "\t--update \tUpdate sphinx config files first"
  exit
elif [[ $1 == "update" || $1 == "--update" ]]; then
  update_config
fi

main "$@"
