#!/usr/bin/env bash

export PATH=$PATH:/usr/local/bin

ND_DIR="/var/www/apps/current"
NODE_ENV="production"

SSH="ssh -t -t user@server"
SEARCHD="sudo /etc/init.d/searchd"
INDEXER="sudo -u sphinx /usr/bin/indexer"

SPHINX_CONF="/etc/sphinx/conf.d/"
INDEX_DIRS="/usr/local/var/data/"
ORGS=( "people" "orchid" )

function main {
  $SSH $SEARCHD stop

  print "> Flushing all indexes.."
  $SSH "cd $INDEX_DIRS;
  for d in "'*'"; do
    echo \"removing all files from $INDEX_DIRS"'$d'\""
    rm -f -v $INDEX_DIRS"'$d/*'"
  done"

  print "> Create sphinx standart indexes.."
  $SSH $INDEXER --all

  $SSH $SEARCHD start

  cd $ND_DIR &&
  print "> Building sphinx rt indexes.."
  for o in "${ORGS[@]}"; do
    print "reindex rt indexes for "$o
    NODE_ENV=$NODE_ENV node tasks $o/reindex
  done
}

function update_config {
  print "Updating sphinx config files.."
  cd $ND_DIR &&
  for o in "${ORGS[@]}"; do
    print "updating config: "$SPHINX_CONF$o.conf
    NODE_ENV=$NODE_ENV node tasks $o/sphinx | $SSH "cat > $SPHINX_CONF$o.conf"
  done
}

function print {
  DEF='\033[0;39m'       #  ${DEF}
  DGRAY='\033[1;30m'     #  ${DGRAY}
  LRED='\033[1;31m'      #  ${LRED}
  LCYAN='\033[1;36m'     #  ${LCYAN}
  LGREEN='\033[1;32m'    #  ${LGREEN}
  LYELLOW='\033[1;33m'   #  ${LYELLOW}
  LBLUE='\033[1;34m'     #  ${LBLUE}
  LMAGENTA='\033[1;35m'  #  ${LMAGENTA}
  if [ -z "$2" ]; then
    echo -e "$LCYAN$1$DEF"
  else
    echo -e "$LRED ERROR: $1$DEF"
  fi
}


if [[ $1 == '-h' || $1 == '--help' ]]; then
  echo -e "Usage: $0 [--update]"
  echo -e "\t--update \tUpdate sphinx config files first"
  exit
elif [[ $1 == "update" || $1 == "--update" ]]; then
  update_config
fi

main "$@"
