#!/usr/bin/env bash

export PATH=$PATH:/usr/local/bin

LOCKFILE="/var/run/sphinx_reindex/`basename $0`.lock"
ND_DIR="/var/www/noodoo/app"
NODE_ENV="sphinx-local"
INDEXER="sudo -u sphinx /usr/bin/indexer"
SPHINX_CONF="/etc/sphinx/conf.d/"
INDEX_DIRS="/usr/local/var/data/"
ORGS=( "people" "shipments" )

function main {
  sudo systemctl stop searchd.service && sleep 10
  print "> Flushing all indexes.."
  cd $INDEX_DIRS &&
  for d in */ ; do
    print "removing all files from $INDEX_DIRS$d"
    rm -fv $INDEX_DIRS$d*
  done

  print "> Load sphinx standart indexes.."
  $INDEXER --all

  sudo systemctl start searchd.service && sleep 10
  
  cd $ND_DIR &&
  print "> Building rt indexes.."
  for o in "${ORGS[@]}"; do
    print "building rt indexes for "$o
    NODE_ENV=$NODE_ENV node tasks $o/reindex
  done
}

function update_config {
  print "Updating sphinx config files.."
  cd $ND_DIR &&
  for o in "${ORGS[@]}"; do
    print "updating config: "$SPHINX_CONF$o.conf
    NODE_ENV=$NODE_ENV timeout 20 node tasks $o/sphinx >$SPHINX_CONF$o.conf
  done
}

function print {
  DEF='\033[0;39m'       #  ${DEF}
  DGRAY='\033[1;30m'     #  ${DGRAY}
  LRED='\033[1;31m'      #  ${LRED}
  LCYAN='\033[1;36m'     #  ${LCYAN}
  LGREEN='\033[1;32m'    #  ${LGREEN}
  LYELLOW='\033[1;33m'   #  ${LYELLOW}
  LBLUE='\033[1;34m'     #  ${LBLUE}
  LMAGENTA='\033[1;35m'  #  ${LMAGENTA}
  if [ -z "$2" ]; then
    echo -e "$LCYAN$1$DEF"
  else
    echo -e "$LRED ERROR: $1$DEF"
  fi
}

function lock {
  if [[ -f $LOCKFILE ]] ; then
    echo 'Another instance is already running. Leaving.'
    exit 1
  fi

  touch $LOCKFILE
  trap "rm -f -- '$LOCKFILE'" EXIT
}

if [[ $1 == '-h' || $1 == '--help' ]]; then
  echo -e "Usage: $0 [--update]"
  echo -e "\t--update \tUpdate sphinx config files first"
  exit
elif [[ $1 == "update" || $1 == "--update" ]]; then
  update_config
fi

lock
main "$@"
